author = "cydave"
title = "PaperMod"
base_url = "https://cydave.github.io/zola-theme-papermod"
compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true


taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

[extra.papermod]
title = "PaperMod"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["keyword1", "keyword2", "keyword3"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
show_post_edit_button = false
edit_post_url = "https://github.com/cydave/zola-theme-papermod/tree/master"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "https://getzola.com/", title = "Zola", is_external = true }
]

home_title = "PaperMod"
home_content = "Welcome to a demo of the PaperMod theme!<br><b>PaperMod</b> is a simple but fast and responsive theme with a useful feature-set that enhances UX.<br>Do give a ðŸŒŸ on Github !<br>PaperMod is based on the hugo-PaperMod theme."
social_icons = [
    { url = "https://github.com/cydave", title = "GitHub", icon = "github" },
    { url = "https://infosec.exchange/@cydave", title = "Mastodon", icon = "mastodon" },
    { url = "https://twitter.com/_cydave", title = "Twitter", icon = "twitter" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
